apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
namespace: prod
images:
- name: harbor.guahao-inc.com/alert-service/gitops
  newTag: master-bdaa801e
