apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops
  name: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
      - image: harbor.guahao-inc.com/alert-service/gitops
        name: gitops
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
          name: http