name: gitops demo

on: [push]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  build:
    needs: golangci
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}

    steps:
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          push: true
          registry: docker.pkg.github.com
          tags: $GITHUB_REF-$SHA8
          tag_with_ref: true


